#!/usr/bin/env bash
# Kvalitetsgate (FR-TEST): pytest, ruff og mypy i demo-repoets egen .venv.
# Rå output og en deterministisk opsummering skrives til reports/raw/ og committes af scriptet,
# så testeren skriver reports/quality.md ud fra tal, som ingen LLM har rørt.
# Brug:  scripts/quality.sh <demo-mappe>      exit 0 = alle tre checks grønne
set -uo pipefail
DEMO="$(cd "${1:?brug: scripts/quality.sh <demo-mappe>}" && pwd)"
RAW="$DEMO/reports/raw"
mkdir -p "$RAW"
cd "$DEMO" || exit 1

declare -A CMDS=(
  [pytest]=".venv/bin/python -m pytest -q --tb=short -p no:cacheprovider"
  [ruff]=".venv/bin/ruff check --output-format concise src tests"
  [mypy]=".venv/bin/mypy"
)
failed=0
rows=""
details=""
for check in pytest ruff mypy; do
  cmd=${CMDS[$check]}
  # shellcheck disable=SC2086
  timeout 300 $cmd >"$RAW/$check.txt" 2>&1
  code=$?
  result=$(grep -v '^\s*$' "$RAW/$check.txt" | tail -n 1)
  rows+="| $check | $cmd | $code | ${result//|//} |"$'\n'
  if [[ $code -ne 0 ]]; then
    failed=1
    details+=$'\n'"## $check (first 40 lines)"$'\n\n'"$(head -n 40 "$RAW/$check.txt" | sed 's/^/    /')"$'\n'
  fi
done

{
  echo "# Raw quality results"
  echo
  echo "Generated by scripts/quality.sh from the toolchain. Agents must not edit this file."
  echo
  echo "| Check | Command | Exit code | Result |"
  echo "|---|---|---|---|"
  printf '%s' "$rows"
  printf '%s' "$details"
} >"$RAW/summary.md"

cat "$RAW/summary.md"
git add reports/raw
git diff --cached --quiet || git commit --quiet -m "quality: rå resultater fra pytest, ruff og mypy"
exit $failed
